CREATE DATABASE COLLEGE;

USE COLLEGE;

CREATE TABLE STUDENT1(
ROLLNO INT PRIMARY KEY,
NAME VARCHAR(20),
MARKS INT NOT NULL,
GRADE VARCHAR(1),
CITY VARCHAR(20)
);

INSERT INTO STUDENT1(ROLLNO,NAME,MARKS,GRADE,CITY) VALUES 
(101,"ANIL",78,"D","PUNE"),
(102,"BHUMIKA",93,"C","MUMBAI"),
(103,"CHETAN",85,"B","DELHI"),
(104,"DHRUV",96,"A","BANGLORE");

INSERT INTO STUDENT1(ROLLNO,NAME,MARKS,GRADE,CITY) VALUES 
(105,"RAMESH",78,"D","PUNE");

SELECT DISTINCT CITY FROM STUDENT1;

SELECT * FROM STUDENT1 WHERE CITY = "PUNE";

SELECT * FROM STUDENT1 ORDER BY NAME ASC; 
SELECT * FROM STUDENT1 ORDER BY CITY DESC;

SELECT * FROM STUDENT1 WHERE NAME = "SALMAN" OR MARKS= 79;

SELECT * FROM STUDENT1 WHERE NOT CITY = "PUNE";


