-- TCL (TRANSCATION CONTROL LANGAUGE)
-- TRANSACTION , COMMIT , ROLLBACK , SAVEPOINT.



CREATE DATABASE TCL;

USE TCL;


CREATE TABLE STUDENT(
STDID INT PRIMARY KEY,
STDNAME VARCHAR(10) NOT NULL,
STDAGE INT NOT NULL
); 

INSERT INTO STUDENT(STDID,STDNAME,STDAGE) VALUES(1,'SALMAN',50),
(2,'SHAHRUKH',30),
(3,'AKSHAY',35),
(4,'HRITIK',56),
(5,'VARUN',65),
(6,'RANBIR',34);

START TRANSACTION;

INSERT INTO STUDENT(STDID,STDNAME,STDAGE) VALUES(7,'JOHN',35);

SELECT * FROM STUDENT;

ROLLBACK;

INSERT INTO STUDENT(STDID,STDNAME,STDAGE) VALUES(8,'RANBIR',35);

COMMIT;

ROLLBACK;

START TRANSACTION;

INSERT INTO STUDENT(STDID,STDNAME,STDAGE) VALUES(9,'PRBHAS',35);

SAVEPOINT PRABHAS;

INSERT INTO STUDENT(STDID,STDNAME,STDAGE) VALUES(10,'YASH',39);

SAVEPOINT YASH;

ROLLBACK TO PRABHAS;


SELECT * FROM STUDENT;






