-- CREATE DATABASE
CREATE DATABASE COLLEGE;

-- USE DATABASE 
USE COLLEGE;

-- CREATE TABLE 
CREATE TABLE STUDENT1(
ROLLNO INT PRIMARY KEY,
NAME VARCHAR(20),
MARKS INT NOT NULL,
GRADE VARCHAR(1),
CITY VARCHAR(20)
);

-- INSERT RECORD 
INSERT INTO STUDENT1(ROLLNO,NAME,MARKS,GRADE,CITY) VALUES 
(101,"ANIL",78,"D","PUNE"),
(102,"BHUMIKA",93,"C","MUMBAI"),
(103,"CHETAN",85,"B","DELHI"),
(104,"DHRUV",96,"A","BANGLORE");

-- INSERT RECORD 
INSERT INTO STUDENT1(ROLLNO,NAME,MARKS,GRADE,CITY) VALUES 
(105,"RAMESH",78,"D","PUNE");

-- GET UNIQUE DATA FROM PARTICULAR COLUMN 
SELECT DISTINCT CITY FROM STUDENT1;

-- WHERE CONDITION FOR GET SPECIFIC ONE TYPES OF DATA
SELECT * FROM STUDENT1 WHERE CITY = "PUNE";

-- GET DATA WITH ACESDING OR DESENDING FORMATE
SELECT * FROM STUDENT1 ORDER BY NAME ASC; 
SELECT * FROM STUDENT1 ORDER BY CITY DESC;

-- LOGICAL OPERATOR 
SELECT * FROM STUDENT1 WHERE NAME = "SALMAN" OR MARKS>= 79;
SELECT * FROM STUDENT1 WHERE NOT CITY = "PUNE";
SELECT * FROM STUDENT1 WHERE NOT CITY = "BANGLORE";

-- CHECK NULL OR NOT 
SELECT NAME,MARKS,GRADE FROM STUDENT1 WHERE GRADE IS NOT NULL;

-- GET PARTICULAR ONE USER DATA
UPDATE STUDENT1 SET NAME = "MAHESH" WHERE ROLLNO = 1;

SELECT * FROM STUDENT1;

-- UPDATE DATA WITH SPECIFIC CONDITION 
UPDATE STUDENT1 SET CITY = "MUMBAI" WHERE CITY = "PUNE";

-- DELETE DATA WITH SPECIFIC CONDITION.
DELETE FROM STUDENT1 WHERE ROLLNO = 2;

-- AGGREGATE FUNCTION
-- MIN , MAX , SUM , COUNT , AVG .alter
SELECT MIN(MARKS) FROM STUDENT1;
SELECT MAX(MARKS) FROM STUDENT1;
SELECT AVG(MARKS) FROM STUDENT1;
SELECT SUM(MARKS) FROM STUDENT1;
SELECT COUNT(MARKS) FROM STUDENT1;

-- LIKE OPERATOR   _  % FOR USE WHERE CLOUSE OR SEARCHING
SELECT * FROM STUDENT1 WHERE NAME LIKE "A%";
SELECT * FROM STUDENT1 WHERE CITY LIKE "%N%";
SELECT * FROM STUDENT1 WHERE CITY LIKE "_%";
SELECT * FROM STUDENT1 WHERE NAME LIKE "B_%";



